version = 0.1

[default.deploy.parameters]
stack_name = "twilio-front-transcribe"
region = "ap-northeast-1"
resolve_s3 = true
s3_prefix = "twilio-front-transcribe"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
